#!/bin/bash
#usage: test.mk.sh <输入> <输出> <test> <测试列表> <忽略列表> <BIOS>

#如果测试列表是@all，则测试test目录下的所有文件夹
if [ "$4" = @all ]
then
	for TEST in $(ls -Cp $3)
	do
		len=$(expr ${#TEST} - 1)
		if [ "${TEST:$len:1}" = "/" ]
		then
			TEST_LIST="$TEST_LIST ${TEST:0:$len}"
		fi
	done
else
	TEST_LIST=$4
fi

TEST_LIST_=$TEST_LIST
TEST_LIST=""
IGNORED_LIST=""
#删除位于忽略列表中的测试
for TEST in $TEST_LIST_
do
	if !(echo "$5 " | grep "$TEST " >/dev/null)
	then
		TEST_LIST="$TEST_LIST $TEST"
	else
		IGNORED_LIST="$IGNORED_LIST $TEST"
	fi
done

for TEST in $TEST_LIST
do
	TEST_LIST_BIN="$TEST_LIST_BIN $TEST.bin"
done

echo List of tests that will run:
echo $TEST_LIST
echo ""
echo List of tests that are ignored:
echo $IGNORED_LIST

echo "# Generated by \`$0\` ." > $2

sed "s/@testlist@/$TEST_LIST_BIN/g" $1.0 >> $2
echo "" >> $2
for TEST in $TEST_LIST
do
	sed "s/@testname@/$TEST/g" $1.1 >> $2
	echo "" >> $2
done

QEMU_VERSION=$(qemu-system-riscv64 -version | grep --basic-regexp 'version *[0-9]*.' --only-matching | grep --basic-regexp '[0-9]*' --only-matching)

echo "" >> $2
echo "run: build" >> $2

for TEST in $TEST_LIST
do
	# old QEMU versions do not support `-kernel` option
	if [ $QEMU_VERSION -ge 6 ]
	then
		KERNEL="-kernel $TEST.bin"
	else
		KERNEL="-device loader,file=$TEST.bin,addr=0x80200000"
	fi

	echo "	@echo Running $TEST..." >> $2
	if [ -f $3/$TEST/run_flags.txt ]
	then
		echo "	@qemu-system-riscv64 -machine virt $(cat $3/$TEST/run_flags.txt) -bios \"$6\" $KERNEL" >> $2
	else
		echo "	@qemu-system-riscv64 -machine virt -nographic -bios $6 $KERNEL" >> $2
	fi
done
