#!/bin/sh

TEST_LIST=$(ls -C $3)

for TEST in $TEST_LIST
do
	TEST_LIST_BIN="$TEST_LIST_BIN $TEST.bin"
done

echo "# Generated by \`$0\` ." > $2

sed "s/@testlist@/$TEST_LIST_BIN/g" $1.0 >> $2
echo "" >> $2
for TEST in $TEST_LIST
do
	sed "s/@testname@/$TEST/g" $1.1 >> $2
	echo "" >> $2
done

echo "" >> $2
echo "run: build" >> $2
for TEST in $TEST_LIST
do
	if [ -f $3/$TEST/run_flags.txt ]
	then
		echo "	qemu-system-riscv64 -machine virt $(cat $3/$TEST/run_flags.txt) -bios \$\$RISCV_BIOS -device loader,file=$TEST.bin,addr=0x80200000" >> $2
	else
		echo "	qemu-system-riscv64 -machine virt -nographic -bios \$\$RISCV_BIOS -device loader,file=$TEST.bin,addr=0x80200000" >> $2
	fi
done
